export default [
	{ name: "Luke Skywalker", riskLevel: "5" },
	{ name: "Han Solo", riskLevel: "5" },
	{ name: "Darth Vader", riskLevel: "5" },
	{ name: "Chewbacca", riskLevel: "5" },
	{ name: "Jabba the Hutt", riskLevel: "5" },
	{ name: "R2D2", riskLevel: "5" },
	{ name: "Yoda", riskLevel: "5" },
	{ name: "C3PO", riskLevel: "5" },
	{ name: "The Emperor", riskLevel: "5" },
	{ name: "Kylo Ren", riskLevel: "5" },
	{ name: "Finn", riskLevel: "5" },
	{ name: "Admiral Ackbar", riskLevel: "5" },
	{ name: "Boba Fett", riskLevel: "5" },
	{ name: "Qui-Gon Jinn", riskLevel: "5" },
	{ name: "General Grievous", riskLevel: "5" },
	{ name: "Poe Dameron", riskLevel: "5" },
	{ name: "Wicket Warrick", riskLevel: "5" },
	{ name: "The Modal Nodes", riskLevel: "5" },
	{ name: "Salacious B Crumb", riskLevel: "5" },
	{ name: "Nien Nunb", riskLevel: "5" },
	{ name: "Count Dooku", riskLevel: "5" },
	{ name: "Uncle Owen", riskLevel: "5" },
	{ name: "Q'ira", riskLevel: "5" },
	{ name: "Sebulba", riskLevel: "5" },
	{ name: "Padme Amidala", riskLevel: "5" },
	{ name: "Jango Fett", riskLevel: "5" },
];
